-- FiveM Luacheck Configuration (ZAWAPPS)
-- Professional configuration with automated native definition support.

std = "lua54"

-- Core System Globals (Manually maintained for fundamental APIs)
globals = {
    "Citizen", "AddEventHandler", "RegisterNetEvent", "TriggerEvent",
    "TriggerServerEvent", "TriggerClientEvent", "RegisterServerEvent",
    "GetConvar", "GetConvarInt", "GetResourceMetadata", "GetCurrentResourceName",
    "Wait", "SetTimeout", "exports", "LocalPlayer", "GlobalState", "Entity", "Player",
    "vec3", "vec2", "vec4", "quat", "CreateThread", "SetTick", "CancelEvent",
    "AddTextEntry", "BeginTextCommand", "EndTextCommand", "GlobalState",
    "ESX", "QBCore", "Config", "MySQL", "Ox", "lib", "Cache", "Global",
    "NDCore", "vRP", "Core", "Events", "State", "_G",
}

-- 🛠 AUTOMATED GLOBAL DEFINITIONS
-- We use 'read_globals' to inject the thousands of FiveM natives dynamically.
-- This file is generated by .github/scripts/sync_natives.py
read_globals = {
    ".github/scripts/natives_defs.lua"
}

-- Custom rules
ignore = { 
    "212", -- Unused argument
    "213", -- Unused loop variable
}

-- Style settings
max_line_length = 200
allow_defined_top = true
